[package]
name = "prometheus-sdk"
version = "1.0.0"
description = "Interact with the Prometheus Protocol using the Motoko programming language"
repository = "https://github.com/prometheus-protocol/motoko-sdk"
keywords = [ ]
license = "MIT"