# .github/workflows/release.yml
name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This is critical for semantic-release to analyze the full commit history
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install # This installs mops, semantic-release, etc. from package.json
      
      - name: Import Mops Identity from Secret
        env:
          # The PEM file content is stored in this secret
          DFX_IDENTITY_PEM: ${{ secrets.DFX_IDENTITY_PEM }}
        # This command configures the mops CLI with the identity for subsequent commands.
        # It does NOT require dfx to be installed.
        run: npx mops user import -- "$DFX_IDENTITY_PEM"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release